# Site settings
title: carrollmusic.net
mgmt_email: haley@saltymgmt.com
booking_email: bojan@rogueagency.us
press_email: debbie@girlie.com
description: > # this means to ignore newlines until "baseurl:"
  Four piece psych pop outfit making every color of wave
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carrollmusic.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
