# Site settings
title: carrollmusic.net
mgmt_email: booking@carrollmusic.net
booking_email: booking@carrollmusic.net
press_email: kelly@wolfievibespublicity.com
description: > # this means to ignore newlines until "baseurl:"
  psych pop 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carrollmusic.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
